-- Process contracts promoted from processes/*.yml. Generated from the kernel parser.
create table if not exists public.process_contracts (
  process_id text primary key,
  title text not null,
  contract jsonb not null,
  status text not null default 'active',
  source_yml text,
  registered_hash text references public.logline_acts(content_hash),
  created_at timestamptz not null default now()
);

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'attention-raise.v1','attention-raise.v1','{"process_id":"attention-raise.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/attention-raise.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'evidence-closure.v1','evidence-closure.v1','{"process_id":"evidence-closure.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/evidence-closure.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'github-check.v1','github-check.v1','{"process_id":"github-check.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/github-check.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'inference.v1','inference.v1','{"process_id":"inference.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["inference"],"danger_tier":"L3","evidence_obligation":"separate-result-act","evidence_must_include":["output_hash","schema_hash"],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/inference.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'memory-register.v1','memory-register.v1','{"process_id":"memory-register.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["receipt"],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/memory-register.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'notification.v1','notification.v1','{"process_id":"notification.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L5","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/notification.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'oauth-client.v1','oauth-client.v1','{"process_id":"oauth-client.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["oauth-client"],"danger_tier":"L3","evidence_obligation":"separate-result-act","evidence_must_include":["request_hash","client_metadata_hash"],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/oauth-client.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'projection-build.v1','projection-build.v1','{"process_id":"projection-build.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["projection"],"danger_tier":"L1","evidence_obligation":"separate-result-act","evidence_must_include":["projection_hashes"],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/projection-build.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'route-to-devin.v1','route-to-devin.v1','{"process_id":"route-to-devin.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":["target_content_hash","target_process"],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["route_to_devin"],"danger_tier":"L4","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/route-to-devin.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'worker-run.v1','worker-run.v1','{"process_id":"worker-run.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["worker_run"],"danger_tier":"L4","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/worker-run.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'workflow-run.v1','workflow-run.v1','{"process_id":"workflow-run.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["workflow_run"],"danger_tier":"L5","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/workflow-run.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;
