-- Process contracts promoted from processes/*.yml. Generated from the kernel parser.
create table if not exists public.process_contracts (
  process_id text primary key,
  title text not null,
  contract jsonb not null,
  status text not null default 'active',
  source_yml text,
  registered_hash text references public.logline_acts(content_hash),
  created_at timestamptz not null default now()
);

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'attention-raise.v1','attention-raise.v1','{"process_id":"attention-raise.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que pede atenção","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"ato de atenção admitido","source":"llm","predicate":"did.allowed","values":["raise_attention"]},"this":{"meaning":"objeto que requer atenção","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do pedido","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma o pedido","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após acolhimento","source":"contract","predicate":"if_ok.compatible","values":["attention-raise.v1"]},"if_doubt":{"meaning":"continuidade se a atenção não puder ser resolvida","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do pedido","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/attention-raise.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'evidence-closure.v1','evidence-closure.v1','{"process_id":"evidence-closure.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita fechamento","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"ato de fechamento admitido","source":"llm","predicate":"did.allowed","values":["close_evidence"]},"this":{"meaning":"processo ou resultado a fechar","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do fechamento","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma a evidência","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após fechamento","source":"contract","predicate":"if_ok.compatible","values":["evidence-closure.v1"]},"if_doubt":{"meaning":"continuidade se a evidência for insuficiente","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do pedido","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/evidence-closure.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'github-check.v1','github-check.v1','{"process_id":"github-check.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita o check","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"ato GitHub admitido","source":"llm","predicate":"did.allowed","values":["create_github_check"]},"this":{"meaning":"commit ou execução alvo","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do check","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma o check","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após check","source":"contract","predicate":"if_ok.compatible","values":["github-check.v1"]},"if_doubt":{"meaning":"continuidade se o check não puder ser provado","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do check","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/github-check.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'inference.v1','inference.v1','{"process_id":"inference.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita inferência","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"pedido de inferência admitido","source":"llm","predicate":"did.allowed","values":["requested_inference"]},"this":{"meaning":"tarefa canônica de inferência","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do pedido","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma o pedido","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após inferência","source":"contract","predicate":"if_ok.compatible","values":["inference.v1"]},"if_doubt":{"meaning":"continuidade se a inferência não for confiável","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade quando não há modelo","source":"contract","predicate":"if_not.compatible","values":["no_model"]},"status":{"meaning":"estado inicial do pedido","source":"contract","predicate":"status.initial","values":["candidate"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["inference"],"danger_tier":"L3","evidence_obligation":"separate-result-act","evidence_must_include":["output_hash","schema_hash"],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/inference.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'memory-register.v1','memory-register.v1','{"process_id":"memory-register.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que registra a memória","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"ato explícito de registro","source":"llm","predicate":"did.allowed","values":["registered"]},"this":{"meaning":"memória ou fato registrado","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante do registro","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma o registro","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após registrar","source":"contract","predicate":"if_ok.compatible","values":["memory-register.v1"]},"if_doubt":{"meaning":"continuidade se o registro exigir atenção","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop","clock.skip"]},"status":{"meaning":"estado inicial do registro","source":"contract","predicate":"status.initial","values":["registered","scheduled"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["receipt"],"danger_tier":"L0","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/memory-register.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'notification.v1','notification.v1','{"process_id":"notification.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita a notificação","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"ato de notificação admitido","source":"llm","predicate":"did.allowed","values":["send_notification"]},"this":{"meaning":"destinatário ou evento notificado","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro da notificação","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma o envio","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após envio","source":"contract","predicate":"if_ok.compatible","values":["notification.v1"]},"if_doubt":{"meaning":"continuidade se o envio não puder ser provado","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial da notificação","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":[],"danger_tier":"L5","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/notification.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'oauth-client.v1','oauth-client.v1','{"process_id":"oauth-client.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita o cliente OAuth","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"registro OAuth admitido","source":"llm","predicate":"did.allowed","values":["register_oauth_client"]},"this":{"meaning":"cliente OAuth a registrar","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do pedido","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma o cliente","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após registrar o cliente","source":"contract","predicate":"if_ok.compatible","values":["oauth-client.v1"]},"if_doubt":{"meaning":"continuidade se o registro não for seguro","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do pedido","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["oauth-client"],"danger_tier":"L3","evidence_obligation":"separate-result-act","evidence_must_include":["request_hash","client_metadata_hash"],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/oauth-client.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'projection-build.v1','projection-build.v1','{"process_id":"projection-build.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita a projeção","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"pedido de projeção admitido","source":"llm","predicate":"did.allowed","values":["request_projection","build_projection"]},"this":{"meaning":"alvo canônico da projeção","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do pedido","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma a projeção","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após materializar","source":"contract","predicate":"if_ok.compatible","values":["projection-build.v1"]},"if_doubt":{"meaning":"continuidade se a projeção não puder ser provada","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do pedido","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["projection"],"danger_tier":"L1","evidence_obligation":"separate-result-act","evidence_must_include":["projection_hashes"],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/projection-build.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'route-to-devin.v1','route-to-devin.v1','{"process_id":"route-to-devin.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita a delegação","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"delegação admitida","source":"llm","predicate":"did.allowed","values":["route_to_devin"]},"this":{"meaning":"trabalho canônico a delegar","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro da delegação","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma a delegação","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após delegar","source":"contract","predicate":"if_ok.compatible","values":["route-to-devin.v1"]},"if_doubt":{"meaning":"continuidade se a delegação não for segura","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial da delegação","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":["target_content_hash","target_process"],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["route_to_devin"],"danger_tier":"L4","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/route-to-devin.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'worker-run.v1','worker-run.v1','{"process_id":"worker-run.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita o worker","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"execução de worker admitida","source":"llm","predicate":"did.allowed","values":["run_worker"]},"this":{"meaning":"trabalho canônico do worker","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do trabalho","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma a execução","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após execução","source":"contract","predicate":"if_ok.compatible","values":["worker-run.v1"]},"if_doubt":{"meaning":"continuidade se a execução não for segura","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do trabalho","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["worker_run"],"danger_tier":"L4","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/worker-run.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;

insert into public.process_contracts(process_id,title,contract,status,source_yml) values (
  'workflow-run.v1','workflow-run.v1','{"process_id":"workflow-run.v1","title":"","status":"active","kind":"","version":"","owner":"","process_class":"","organ":"law","wakes":[],"requires_infra":[],"composable":false,"requires_target_hash":false,"idempotency":"none","evidence_required":false,"required_slots":["who","did","this","when","confirmed_by","if_ok","if_doubt","if_not","status"],"slot_rules":{"who":{"meaning":"autoridade que solicita o workflow","source":"session","predicate":"who.authorized","values":[]},"did":{"meaning":"execução de workflow admitida","source":"llm","predicate":"did.allowed","values":["run_workflow"]},"this":{"meaning":"workflow canônico a executar","source":"llm","predicate":"this.canonical","values":[]},"when":{"meaning":"instante de registro do workflow","source":"clock","predicate":"when.registered_at","values":[]},"confirmed_by":{"meaning":"autoridade que confirma a orquestração","source":"session","predicate":"confirmed_by.authority","values":[]},"if_ok":{"meaning":"continuidade após orquestração","source":"contract","predicate":"if_ok.compatible","values":["workflow-run.v1"]},"if_doubt":{"meaning":"continuidade se a orquestração não for segura","source":"contract","predicate":"if_doubt.compatible","values":["attention-raise.v1"]},"if_not":{"meaning":"continuidade negativa","source":"contract","predicate":"if_not.compatible","values":["stop"]},"status":{"meaning":"estado inicial do workflow","source":"contract","predicate":"status.initial","values":["registered"]}},"activation_rules_explicit":true,"must_include":[],"optional_aux":[],"allowed_who":[],"required_grants":[],"adapters":["workflow_run"],"danger_tier":"L5","evidence_obligation":"separate-result-act","evidence_must_include":[],"budget_policy":{},"closure_shape":{},"if_doubt_behavior":"attention_raise","runtime_readiness_checks":[],"doubt_path":"attention-raise.v1"}'::jsonb,'active','processes/workflow-run.v1.yml'
) on conflict (process_id) do update set title=excluded.title, contract=excluded.contract, status=excluded.status, source_yml=excluded.source_yml;
