// Closed failure vocabulary from lab/messages.py — 27 codes, no hardcode in UI.
// Served by GET /api/vocabulary so UI renders without release when a reason is added.
export const CATALOG: Record<string, [string, string, string]> = {
  "no_matching_process_contract": ["Ficou registrado, mas não há um tipo de solicitação que case com isto.", "Escolher tipo", "user"],
  "process_not_active": ["Este tipo de solicitação está desativado no momento.", "Avisar responsável", "operator"],
  "incomplete": ["Para andar, falta: {campos}.", "Completar", "user"],
  "no_adapter_configured": ["Este tipo existe, mas ainda não executa nada.", "Avisar responsável", "operator"],
  "adapter_not_registered": ["A ação que este tipo pede ainda não existe neste sistema.", "Avisar responsável", "operator"],
  "dispatch_mismatch": ["A solicitação foi preparada com uma ação diferente da que a regra pede agora. Nada foi executado.", "Reenviar", "user"],
  "missing_required_grant": ["Para andar, precisa de autorização assinada.", "Pedir autorização", "user"],
  "grant_not_found": ["A autorização indicada não existe.", "Pedir autorização", "user"],
  "grant_subject_mismatch": ["Esta autorização foi dada para outra pessoa.", "Pedir autorização", "user"],
  "grant_process_mismatch": ["Esta autorização não vale para este tipo de solicitação.", "Pedir autorização", "user"],
  "grant_adapter_mismatch": ["Esta autorização não cobre a ação que seria executada.", "Pedir autorização", "user"],
  "who_not_authorized": ["Você não está na lista de quem pode fazer isto.", "Pedir acesso", "user"],
  "grant_not_active": ["Esta autorização não está ativa.", "Pedir autorização", "user"],
  "grant_revoked": ["Esta autorização foi cancelada.", "Pedir autorização", "user"],
  "grant_expired": ["A autorização venceu em {data}.", "Renovar", "user"],
  "budget_exhausted": ["O limite de uso desta autorização acabou.", "Pedir aumento", "user"],
  "missing_grant_expiry": ["A autorização não tem prazo de validade. Por segurança, não vale.", "Avisar responsável", "operator"],
  "missing_timeout": ["A autorização não define tempo limite de execução.", "Avisar responsável", "operator"],
  "missing_sandbox_scope": ["A autorização não define onde a ação pode mexer.", "Avisar responsável", "operator"],
  "missing_network_policy": ["A autorização não define o que a ação pode acessar na rede.", "Avisar responsável", "operator"],
  "missing_authority": ["Não foi informado quem autoriza.", "Avisar responsável", "operator"],
  "unregistered_authority": ["Quem concedeu não está registrado como autorizador.", "Avisar responsável", "operator"],
  "grant_unsigned": ["A autorização ainda não foi assinada com chave de segurança.", "Assinar", "user"],
  "signoff_signer_mismatch": ["A assinatura é de outra pessoa, não de quem concedeu a autorização.", "Assinar de novo", "user"],
  "signature_layer_unavailable": ["A verificação por chave de segurança não está disponível neste dispositivo.", "Ver como habilitar", "operator"],
  "evidence_obligation_unmet": ["A ação rodou, mas não comprovou {campos}. Nada foi dado como concluído.", "Ver o que foi produzido", "operator"],
  "adapter_rejected": ["A ação foi recusada com segurança: {motivo}.", "Ver detalhe", "operator"],
};
