// Closed failure vocabulary from lab/messages.py — no hardcode in UI.
// Served by GET /api/vocabulary so UI renders without release when a reason is added.
export const CATALOG: Record<string, [string, string, string]> = {
  "unknown_process": ["Ficou registrado, mas o tipo de processo solicitado não existe no catálogo atual.", "Escolher tipo", "user"],
  "process_route_mismatch": ["O processo endereçado pela rota não é o mesmo declarado no registro. Nada foi executado.", "Ver integração", "operator"],
  "process_not_active": ["Este tipo de solicitação está desativado no momento.", "Avisar responsável", "operator"],
  "incomplete": ["Para andar, falta: {campos}.", "Completar", "user"],
  "activation_rules_not_explicit": ["Este tipo existe, mas ainda não publicou regras semânticas completas para ativação.", "Avisar responsável", "operator"],
  "did_not_admitted": ["O ato informado não é admitido por este tipo de processo.", "Reformular pedido", "user"],
  "confirmed_by_not_authorized": ["A confirmação informada não pertence a uma autoridade admitida por este processo.", "Confirmar novamente", "user"],
  "this_not_canonical": ["O alvo informado não é uma referência canônica válida para este processo.", "Corrigir alvo", "user"],
  "this_not_content_hash": ["Este processo exige que o alvo seja um hash de conteúdo de 64 caracteres.", "Corrigir alvo", "user"],
  "when_invalid": ["O instante informado não é uma data ISO 8601 com fuso horário.", "Corrigir data", "user"],
  "when_not_future": ["Este processo exige um instante futuro, mas a data informada já passou.", "Escolher outra data", "user"],
  "confirmation_evidence_invalid": ["A confirmação não contém o hash de evidência exigido por este processo.", "Fornecer evidência", "user"],
  "if_ok_incompatible": ["A continuidade de sucesso não corresponde ao contrato citado.", "Ver composição", "operator"],
  "if_doubt_incompatible": ["A continuidade de dúvida não corresponde ao contrato citado.", "Ver composição", "operator"],
  "if_not_incompatible": ["A continuidade negativa não corresponde ao contrato citado.", "Ver composição", "operator"],
  "status_initial_invalid": ["O estado inicial não é admitido pelo contrato deste processo.", "Ver composição", "operator"],
  "unknown_predicate": ["O contrato usa um predicado de ativação que este runtime não implementa.", "Corrigir contrato", "operator"],
  "no_adapter_configured": ["Este tipo existe, mas ainda não executa nada.", "Avisar responsável", "operator"],
  "adapter_not_registered": ["A ação que este tipo pede ainda não existe neste sistema.", "Avisar responsável", "operator"],
  "dispatch_mismatch": ["A solicitação foi preparada com uma ação diferente da que a regra pede agora. Nada foi executado.", "Reenviar", "user"],
  "missing_required_grant": ["Para andar, precisa de autorização assinada.", "Pedir autorização", "user"],
  "grant_not_found": ["A autorização indicada não existe.", "Pedir autorização", "user"],
  "grant_subject_mismatch": ["Esta autorização foi dada para outra pessoa.", "Pedir autorização", "user"],
  "grant_process_mismatch": ["Esta autorização não vale para este tipo de solicitação.", "Pedir autorização", "user"],
  "grant_adapter_mismatch": ["Esta autorização não cobre a ação que seria executada.", "Pedir autorização", "user"],
  "who_not_authorized": ["Você não está na lista de quem pode fazer isto.", "Pedir acesso", "user"],
  "grant_not_active": ["Esta autorização não está ativa.", "Pedir autorização", "user"],
  "grant_revoked": ["Esta autorização foi cancelada.", "Pedir autorização", "user"],
  "grant_expired": ["A autorização venceu em {data}.", "Renovar", "user"],
  "budget_exhausted": ["O limite de uso desta autorização acabou.", "Pedir aumento", "user"],
  "missing_grant_expiry": ["A autorização não tem prazo de validade. Por segurança, não vale.", "Avisar responsável", "operator"],
  "missing_timeout": ["A autorização não define tempo limite de execução.", "Avisar responsável", "operator"],
  "missing_sandbox_scope": ["A autorização não define onde a ação pode mexer.", "Avisar responsável", "operator"],
  "missing_network_policy": ["A autorização não define o que a ação pode acessar na rede.", "Avisar responsável", "operator"],
  "missing_authority": ["Não foi informado quem autoriza.", "Avisar responsável", "operator"],
  "unregistered_authority": ["Quem concedeu não está registrado como autorizador.", "Avisar responsável", "operator"],
  "grant_unsigned": ["A autorização ainda não foi assinada com chave de segurança.", "Assinar", "user"],
  "signoff_signer_mismatch": ["A assinatura é de outra pessoa, não de quem concedeu a autorização.", "Assinar de novo", "user"],
  "signature_layer_unavailable": ["A verificação por chave de segurança não está disponível neste dispositivo.", "Ver como habilitar", "operator"],
  "evidence_obligation_unmet": ["A ação rodou, mas não comprovou {campos}. Nada foi dado como concluído.", "Ver o que foi produzido", "operator"],
  "adapter_rejected": ["A ação foi recusada com segurança: {motivo}.", "Ver detalhe", "operator"],
};
